name: EnderChest
version: ${project.version}
main: com.github.happyrogelio7.enderchest.EnderChest
api-version: 1.16
authors: [ HappyRogelio7 ]
description: EnderChest Command plugin
website: https://github.com/HappyRogelio7
commands:

  enderchest:
    aliases: [ec]
    usage: /<command>

  enderchesthelp:
    aliases: [echelp]
    usage: /<command>
